api_platform:
    title: 'BNI API'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header        
    show_webby: false

    defaults:
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
            maximum_items_per_page: 30
            items_per_page: 15
